name: UltimateVote
version: 1.7
api: 5.0.0
author: AppGallery
main: AppGallery\ultimatevote\UltimateVote
permissions:
  ultimateVote.command.vote:
    default: true
    description: "Default UltimateVote permission"